%structure_content

if exist('structure','var')
    s_struct = size(structure,2)+1;
else
    s_struct = 1;
end
if exist('D_h','var')==0; D_h = []; end
if exist('W_h','var')==0; W_h = []; end


structure(s_struct) = struct('material',structure_material,'fiber_type',...
  fiber_type,'DOF',[DOF,n,nzeta,n_y],'properties',[lh;lalpha;lmat;lfib;...
  lvol;lh_f;lh_w;la_f;la_w;lphi_x;lphi_y;lg_f;lg_w;D_h;W_h],'damp_coef',alpha,...
  'typeProp',typeProp,'stShape',stShape,'stAttach',stAttach,...
  'damage_file',name_delam,'geometry',[Lx;Ly;Lz;shiftX;shiftY;shiftZ],...
  'BC',BC,'mesh_type',mesh_type,'inputfile',inputfile,...
  'numElements',[numberElementsX;numberElementsY;numberElementsZ],...
  'piezo_type',piezo_type,'Pn',Pn,...
  'forceNode_range',forceNode_range);

