%structure_content

if exist('structure','var')
    s_struct=size(structure,2)+1;
else
    s_struct=1;
end
if exist('D_h','var')==0; D_h=[]; end
if exist('W_h','var')==0; W_h=[]; end


structure(s_struct)=struct('material',structure_material,'fiber_type',...
  fiber_type,'DOF',[DOF,n,nzeta],'properties',[lh;lalpha;lmat;lfib;...
  lvol;lh_f;lh_w;la_f;la_w;lphi_x;lphi_y;lg_f;lg_w;D_h;W_h],'damp_coef',alpha,...
  'typeProp',typeProp,'stShape',stShape,'stAttach',stAttach,...
  'interfaceElements',interfaceElements,'int_file',name_interface,...
  'damage_file',name_delam,'geometry',[Lx;Ly;Lz;shiftX;shiftY;shiftZ],...
  'BC',BC,'plotSt',plotSt,'mesh_type',mesh_type,'inputfile',inputfile,...
  'numElements',[numberElementsX;numberElementsY;numberElementsZ],...
  'piezo_type',piezo_type,'epsS',epsS,'e_p',e_p,'Pn',Pn,...
  'forceNode_range',forceNode_range,'output_result',output_result);

